## 0.0.11/20211007-12:18:14
- Fixes: TypeError: __init__() missing 1 required positional argument: 'msg' ebench.py
- Features added:
  - command parameter may given in any order